# Generated by Django 5.1.2 on 2024-10-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
