# Generated by Django 5.1.2 on 2024-11-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_alter_subtasks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
