# Generated by Django 5.1.2 on 2024-11-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_alter_category_options_alter_names_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name': 'Taskstatus', 'verbose_name_plural': 'Taskstatus'},
        ),
        migrations.AlterField(
            model_name='names',
            name='email',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='names',
            name='phone',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
