# Generated by Django 5.1.2 on 2024-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_alter_tasks_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='title',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
