# Generated by Django 5.1.2 on 2024-11-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0008_alter_subtasks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='subtask',
        ),
        migrations.AddField(
            model_name='subtasks',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_app.tasks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtasks',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
