# Generated by Django 5.1.2 on 2024-11-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0009_remove_tasks_subtask_subtasks_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='subtasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Subtasks',
        ),
    ]
