# Generated by Django 5.1.2 on 2024-11-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0010_tasks_subtasks_delete_subtasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='assigned_to',
            new_name='assignto',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='due_date',
            new_name='duedate',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='priority',
            new_name='prio',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='subtasks',
            new_name='subtask',
        ),
    ]
