# Generated by Django 5.1.2 on 2024-11-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0011_rename_assigned_to_tasks_assignto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
