# Generated by Django 5.1.2 on 2024-11-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0012_tasks_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
    ]
