# Generated by Django 5.1.2 on 2024-11-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0013_remove_tasks_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Prio', 'verbose_name_plural': 'Priorities'},
        ),
    ]
