# Generated by Django 5.1.2 on 2024-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0014_alter_priority_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='phone',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
