# Generated by Django 5.1.2 on 2024-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0016_alter_tasks_assignto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assignto',
            field=models.ManyToManyField(related_name='tasks', to='join_app.names'),
        ),
    ]
