# Generated by Django 5.1.2 on 2024-12-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0018_alter_tasks_assignto'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='inizialized',
            field=models.BooleanField(default=False),
        ),
    ]
