# Generated by Django 5.1.2 on 2024-12-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0019_names_inizialized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='inizialized',
        ),
    ]
