# Generated by Django 5.1.2 on 2024-12-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0020_remove_names_inizialized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialized', models.BooleanField(default=False)),
            ],
        ),
    ]
