# Generated by Django 5.1.2 on 2024-12-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0021_database'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
    ]
