# Generated by Django 5.1.2 on 2024-12-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacyCheckBox',
            field=models.BooleanField(default=False),
        ),
    ]
