# Generated by Django 5.1.2 on 2024-12-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='privacyCheckBox',
        ),
    ]
