# Generated by Django 5.1.2 on 2024-12-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0005_remove_userprofile_privacycheckbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
